# Generated by Django 3.1 on 2020-09-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200921_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='profile/images', verbose_name='Image'),
        ),
    ]
