# Generated by Django 3.1 on 2020-09-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200921_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='profile/images/default.png', upload_to='profile/images', verbose_name='Image'),
        ),
    ]
